image: docker.basalam.dev/python:3.6-slim

stages:
  - deploy

before_script:
  - pip install twine
  - python setup.py sdist

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* --verbose
  only:
    - tags
